AWSTemplateFormatVersion: "2010-09-09"
Description: "PIA - WebAPI"

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#

Parameters:

  ProjectName:
    Description: "Project Name"
    Type: "String"
    Default: "pia"

  PurposeName:
    Description: "Purpose Name"
    Type: "String"
    Default: "demo"

  CpuUnit:
    Description: "CPU unit number of task"
    Type: "Number"
    Default: 2048

  MemorySize:
    Description: "Memory MiB number of task"
    Type: "Number"
    Default: 4096

  ManagedRulesCountMode:
    Description: Choose whether to set waf managed rules in count mode.
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

Conditions:
  IsCountMode: !Equals
    - !Ref ManagedRulesCountMode
    - true

# ------------------------------------------------------------#
# Resources
# ------------------------------------------------------------#

Resources:
  AccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-${PurposeName}-AppRunnerECRAccessRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  APIInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - tasks.apprunner.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "AllowAccess"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                Resource:
                  - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*

  APIServiceAutoScalingConfiguration:
    Type: AWS::AppRunner::AutoScalingConfiguration
    Properties:
      AutoScalingConfigurationName: !Sub ${ProjectName}-${PurposeName}-AutoScaling
      MaxConcurrency: 100
      MaxSize: 25
      MinSize: 1

  APIService:
    Type: AWS::AppRunner::Service
    Properties:
      AutoScalingConfigurationArn: !GetAtt APIServiceAutoScalingConfiguration.AutoScalingConfigurationArn
      HealthCheckConfiguration:
        Path: /api/health
        Protocol: HTTP
      ServiceName: !Sub ${ProjectName}-${PurposeName}-webapi
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt "AccessRole.Arn"
        AutoDeploymentsEnabled: true
        ImageRepository:
          ImageIdentifier: !Sub
            - "${WebAPIRepositoryUri}:${ImageTag}"
            - WebAPIRepositoryUri:
                { Fn::ImportValue: !Sub "${ProjectName}-${PurposeName}-repository-uri" }
              ImageTag: latest
          ImageRepositoryType: "ECR"
          ImageConfiguration:
            Port: 80
            RuntimeEnvironmentSecrets:
              - Name: OPENAI_API_KEY
                Value: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/twilio-openai-api-key"
      InstanceConfiguration:
        Cpu: !Ref CpuUnit
        Memory: !Ref MemorySize
        InstanceRoleArn: !GetAtt "APIInstanceRole.Arn"

# ------------------------------------------------------------#
# IPSet
# ------------------------------------------------------------#
  # App Runner WAF 用 開発拠点 IPSet
  DeveloperIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: !Sub ${ProjectName}-${PurposeName}-developers-api
      Description: !Sub ${ProjectName}-${PurposeName}-developers-api
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses:
        # Fenrir
        - "42.125.229.42/32"
        - "137.83.213.180/32"
        - "137.83.213.197/32"
        - "134.238.7.18/32"
        - "134.238.7.37/32"
        - "137.83.213.182/32"
        - "208.127.111.171/32"
        - "133.242.224.4/32"
        # pia
        - "202.238.174.38/32"
        - "150.195.219.184/32"
        - "150.195.211.98/32"

# ------------------------------------------------------------#
# WAF for App Runner
# ------------------------------------------------------------#
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub ${ProjectName}-${PurposeName}-WebACL-api
      Scope: REGIONAL
      DefaultAction:
         Block: {} #検証環境の場合はBlock
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub ${ProjectName}-${PurposeName}-WebACL-api
      Rules:
        # - Name: allow-only-custom-domain
        #   Priority: 0
        #   Action:
        #     Block: {}
        #   Statement:
        #     NotStatement:
        #       Statement:
        #         ByteMatchStatement:
        #           FieldToMatch:
        #             SingleHeader:
        #               Name: host
        #           PositionalConstraint: EXACTLY
        #           SearchString: !Ref CustomDomain
        #           TextTransformations:
        #             - Priority: 0
        #               Type: LOWERCASE
        #   VisibilityConfig:
        #     SampledRequestsEnabled: true
        #     CloudWatchMetricsEnabled: true
        #     MetricName: allow-only-custom-domain
        - Name: CoreRuleSet
          Priority: 1
          OverrideAction: !If
            - IsCountMode
            - Count: {}
            - None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            SampledRequestsEnabled: true
            MetricName: CoreRuleSet
        - Name: KnownBadInputs
          OverrideAction: !If
            - IsCountMode
            - Count: {}
            - None: {}
          Priority: 2
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            SampledRequestsEnabled: true
            MetricName: KnownBadInputs
        - Name: LinuxOperatingSystem
          OverrideAction: !If
            - IsCountMode
            - Count: {}
            - None: {}
          Priority: 3
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesLinuxRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            SampledRequestsEnabled: true
            MetricName: LinuxOperatingSystem
        - Name: POSIXOperatingSystem
          OverrideAction: !If
            - IsCountMode
            - Count: {}
            - None: {}
          Priority: 4
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesUnixRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            SampledRequestsEnabled: true
            MetricName: POSIXOperatingSystem
        - Name: AmazonIPReputationList
          OverrideAction: !If
            - IsCountMode
            - Count: {}
            - None: {}
          Priority: 5
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AmazonIPReputationList
            SampledRequestsEnabled: true
        - Name: AnonymousIPList
          OverrideAction: !If
            - IsCountMode
            - Count: {}
            - None: {}
          Priority: 6
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAnonymousIpList
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            SampledRequestsEnabled: true
            MetricName: AnonymousIPList
        - Name: ipv4-addresses-white-list
          Priority: 7
          Action:
            Allow: {}
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt DeveloperIPSet.Arn
          VisibilityConfig:
            SampledRequestsEnabled: true
            MetricName: ipv4-addresses-white-list
            CloudWatchMetricsEnabled: true

  WebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      WebACLArn: !GetAtt WebACL.Arn
      ResourceArn: !GetAtt APIService.ServiceArn
